[2025-04-18T19:00:11.759+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T19:00:11.782+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.download_data scheduled__2025-04-18T18:00:00+00:00 [queued]>
[2025-04-18T19:00:11.795+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.download_data scheduled__2025-04-18T18:00:00+00:00 [queued]>
[2025-04-18T19:00:11.796+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-18T19:00:11.824+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_data> on 2025-04-18 18:00:00+00:00
[2025-04-18T19:00:11.837+0000] {standard_task_runner.py:72} INFO - Started process 3014 to run task
[2025-04-18T19:00:11.842+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'download_data', 'scheduled__2025-04-18T18:00:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmps1bldf3y']
[2025-04-18T19:00:11.851+0000] {standard_task_runner.py:105} INFO - Job 92: Subtask download_data
[2025-04-18T19:00:11.880+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-18T19:00:11.936+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.download_data scheduled__2025-04-18T18:00:00+00:00 [running]> on host e8dafad5cd22
[2025-04-18T19:00:11.941+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-18T19:00:12.153+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-18T18:00:00+00:00'
[2025-04-18T19:00:12.156+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T19:00:12.206+0000] {data_pipeline.py:51} INFO - Executing script: /opt/airflow/scripts/data_acquisition.py
[2025-04-18T19:41:02.420+0000] {job.py:229} INFO - Heartbeat recovered after 2425.21 seconds
[2025-04-18T19:41:20.302+0000] {data_pipeline.py:53} INFO - Successfully executed: /opt/airflow/scripts/data_acquisition.py
[2025-04-18T19:41:20.305+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-18T19:41:20.332+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T19:41:20.335+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=download_data, run_id=scheduled__2025-04-18T18:00:00+00:00, execution_date=20250418T180000, start_date=20250418T190011, end_date=20250418T194120
[2025-04-18T19:41:20.412+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T19:41:20.478+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-18T19:41:20.487+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
