[2025-03-03T04:00:13.961+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T04:00:13.981+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.preprocess_data scheduled__2025-03-03T03:00:00+00:00 [queued]>
[2025-03-03T04:00:13.993+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.preprocess_data scheduled__2025-03-03T03:00:00+00:00 [queued]>
[2025-03-03T04:00:13.995+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-03T04:00:14.045+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): preprocess_data> on 2025-03-03 03:00:00+00:00
[2025-03-03T04:00:14.054+0000] {standard_task_runner.py:72} INFO - Started process 789 to run task
[2025-03-03T04:00:14.059+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'preprocess_data', 'scheduled__2025-03-03T03:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp92rgt45j']
[2025-03-03T04:00:14.063+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask preprocess_data
[2025-03-03T04:00:14.098+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T04:00:14.153+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.preprocess_data scheduled__2025-03-03T03:00:00+00:00 [running]> on host b5502d51568b
[2025-03-03T04:00:14.158+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T04:00:14.274+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T03:00:00+00:00'
[2025-03-03T04:00:14.276+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T04:00:14.295+0000] {data_pipeline.py:63} INFO - Running script: /opt/airflow/scripts/data_preprocessing.py
[2025-03-03T04:00:14.448+0000] {data_pipeline.py:67} ERROR - Error executing /opt/airflow/scripts/data_preprocessing.py: Command '['python', '/opt/airflow/scripts/data_preprocessing.py']' returned non-zero exit status 1.
[2025-03-03T04:00:14.449+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T04:00:14.456+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T04:00:14.457+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=preprocess_data, run_id=scheduled__2025-03-03T03:00:00+00:00, execution_date=20250303T030000, start_date=20250303T040013, end_date=20250303T040014
[2025-03-03T04:00:14.525+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T04:00:14.546+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-03T04:00:14.555+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
