[2025-03-03T02:06:27.169+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T02:06:27.193+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.preprocess_data scheduled__2025-03-03T01:00:00+00:00 [queued]>
[2025-03-03T02:06:27.215+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.preprocess_data scheduled__2025-03-03T01:00:00+00:00 [queued]>
[2025-03-03T02:06:27.224+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-03T02:06:27.274+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): preprocess_data> on 2025-03-03 01:00:00+00:00
[2025-03-03T02:06:27.303+0000] {standard_task_runner.py:72} INFO - Started process 266 to run task
[2025-03-03T02:06:27.311+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'preprocess_data', 'scheduled__2025-03-03T01:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpy1n36pi3']
[2025-03-03T02:06:27.317+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask preprocess_data
[2025-03-03T02:06:27.361+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:06:27.400+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.preprocess_data scheduled__2025-03-03T01:00:00+00:00 [running]> on host 71fb9604a64f
[2025-03-03T02:06:27.406+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:06:27.596+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T01:00:00+00:00'
[2025-03-03T02:06:27.602+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T02:06:27.646+0000] {data_pipeline.py:63} INFO - Running script: /opt/airflow/scripts/data_preprocessing.py
[2025-03-03T02:08:57.815+0000] {data_pipeline.py:65} INFO - Successfully executed: /opt/airflow/scripts/data_preprocessing.py
[2025-03-03T02:08:57.816+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T02:08:57.825+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T02:08:57.826+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=preprocess_data, run_id=scheduled__2025-03-03T01:00:00+00:00, execution_date=20250303T010000, start_date=20250303T020627, end_date=20250303T020857
[2025-03-03T02:08:57.930+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T02:08:57.951+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-03T02:08:57.960+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-03T02:27:20.476+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T02:27:20.493+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.preprocess_data scheduled__2025-03-03T01:00:00+00:00 [queued]>
[2025-03-03T02:27:20.503+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.preprocess_data scheduled__2025-03-03T01:00:00+00:00 [queued]>
[2025-03-03T02:27:20.505+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-03T02:27:20.520+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): preprocess_data> on 2025-03-03 01:00:00+00:00
[2025-03-03T02:27:20.525+0000] {standard_task_runner.py:72} INFO - Started process 129 to run task
[2025-03-03T02:27:20.528+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'preprocess_data', 'scheduled__2025-03-03T01:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpsjoau4_1']
[2025-03-03T02:27:20.531+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask preprocess_data
[2025-03-03T02:27:20.555+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:27:20.593+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.preprocess_data scheduled__2025-03-03T01:00:00+00:00 [running]> on host b5502d51568b
[2025-03-03T02:27:20.595+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:27:20.667+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T01:00:00+00:00'
[2025-03-03T02:27:20.668+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T02:27:20.687+0000] {data_pipeline.py:63} INFO - Running script: /opt/airflow/scripts/data_preprocessing.py
[2025-03-03T02:27:20.842+0000] {data_pipeline.py:67} ERROR - Error executing /opt/airflow/scripts/data_preprocessing.py: Command '['python', '/opt/airflow/scripts/data_preprocessing.py']' returned non-zero exit status 1.
[2025-03-03T02:27:20.843+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T02:27:20.850+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T02:27:20.851+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=preprocess_data, run_id=scheduled__2025-03-03T01:00:00+00:00, execution_date=20250303T010000, start_date=20250303T022720, end_date=20250303T022720
[2025-03-03T02:27:20.910+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T02:27:20.935+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-03T02:27:20.942+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
