[2025-03-02T17:45:15.394+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T17:45:15.414+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.clean_data manual__2025-03-02T17:39:43.662871+00:00 [queued]>
[2025-03-02T17:45:15.424+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.clean_data manual__2025-03-02T17:39:43.662871+00:00 [queued]>
[2025-03-02T17:45:15.425+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-02T17:45:15.455+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): clean_data> on 2025-03-02 17:39:43.662871+00:00
[2025-03-02T17:45:15.462+0000] {standard_task_runner.py:72} INFO - Started process 146 to run task
[2025-03-02T17:45:15.466+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'clean_data', 'manual__2025-03-02T17:39:43.662871+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmphzcogmuu']
[2025-03-02T17:45:15.469+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask clean_data
[2025-03-02T17:45:15.489+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-02T17:45:15.517+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.clean_data manual__2025-03-02T17:39:43.662871+00:00 [running]> on host 150a7fb033c6
[2025-03-02T17:45:15.645+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='clean_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T17:39:43.662871+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T17:39:43.662871+00:00'
[2025-03-02T17:45:15.647+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-02T17:45:15.672+0000] {data_pipeline.py:51} INFO - Executing script: /opt/airflow/scripts/data_preprocessing.py
[2025-03-02T17:47:24.828+0000] {data_pipeline.py:53} INFO - Successfully executed: /opt/airflow/scripts/data_preprocessing.py
[2025-03-02T17:47:24.831+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-02T17:47:24.844+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-02T17:47:24.845+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=clean_data, run_id=manual__2025-03-02T17:39:43.662871+00:00, execution_date=20250302T173943, start_date=20250302T174515, end_date=20250302T174724
[2025-03-02T17:47:24.929+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-02T17:47:24.951+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-02T17:47:24.956+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
